# Generated by Django 4.1.1 on 2022-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xai_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongNormalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('year', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('valence', models.FloatField()),
                ('liveness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
